# Generated by Django 2.1.2 on 2018-10-05 00:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Dominio',
                'verbose_name': 'Dominio',
                'permissions': (('add_dominio', 'Puede agregar Dominio'), ('change_dominio', 'Puede actualizar Dominio'), ('delete_dominio', 'Puede eliminar Dominio'), ('list_dominio', 'Puede listar Dominio'), ('get_dominio', 'Puede obtener Dominio')),
                'db_table': 'atencion_dominio',
                'default_permissions': (),
            },
        ),
    ]
