# Generated by Django 2.1.2 on 2018-10-05 00:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Clase',
                'permissions': (('addd_clase', 'Puede agregar Clase'), ('changed_clase', 'Puede actualizar Clase'), ('deleted_clase', 'Puede eliminar Clase'), ('listd_clase', 'Puede listar Clase'), ('getd_clase', 'Puede obtener Clase')),
                'db_table': 'atenciond_clase',
                'verbose_name': 'Clase',
                'default_permissions': (),
            },
        ),
        migrations.AlterField(
            model_name='dominio',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='clase',
            name='dominio',
            field=models.ForeignKey(db_column='dominio_id', on_delete=django.db.models.deletion.CASCADE, related_name='clase_dominio_set', to='atencion.Dominio'),
        ),
    ]
