# Generated by Django 2.1.2 on 2018-10-05 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0002_auto_20181005_0031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dominio',
            options={'default_permissions': (), 'ordering': ('id',), 'permissions': (('add_dominio', 'Puede agregar Dominio'), ('change_dominio', 'Puede actualizar Dominio'), ('delete_dominio', 'Puede eliminar Dominio'), ('list_dominio', 'Puede listar Dominio'), ('get_dominio', 'Puede obtener Dominio')), 'verbose_name': 'Dominio', 'verbose_name_plural': 'Dominio'},
        ),
    ]
