# Generated by Django 2.1.2 on 2018-10-05 13:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0003_auto_20181005_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxonomia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('abreviatura', models.CharField(max_length=200, unique=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('id',),
                'default_permissions': (),
                'verbose_name_plural': 'Taxonomia',
                'permissions': (('add_taxonomia', 'Puede agregar Taxonomia'), ('change_taxonomia', 'Puede actualizar Taxonomia'), ('delete_taxonomia', 'Puede eliminar Taxonomia'), ('list_taxonomia', 'Puede listar Taxonomia'), ('get_taxonomia', 'Puede obtener Taxonomia')),
                'db_table': 'atencion_taxonomia',
                'verbose_name': 'Taxonomia',
            },
        ),
    ]
