# Generated by Django 2.1.2 on 2018-10-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0004_taxonomia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomia',
            name='codigo',
            field=models.CharField(choices=[('NIC', 'NIC'), ('NOC', 'NOC')], max_length=50, unique=True),
        ),
    ]
