# Generated by Django 2.1.2 on 2018-10-05 13:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0005_auto_20181005_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Domain',
                'ordering': ('id',),
                'db_table': 'atencion_domain',
                'verbose_name_plural': 'Domain',
            },
        ),
    ]
