# Generated by Django 2.1.2 on 2018-10-05 13:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0006_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('domain', models.ForeignKey(db_column='domain_id', on_delete=django.db.models.deletion.CASCADE, related_name='class_dominio_set', to='atencion.Domain')),
            ],
            options={
                'verbose_name': 'Class',
                'db_table': 'atenciond_class',
                'verbose_name_plural': 'Class',
            },
        ),
    ]
