# Generated by Django 2.1.2 on 2018-10-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0009_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='orden',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
