# Generated by Django 2.1.2 on 2018-10-05 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0011_taxonomy'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='taxonomy',
            field=models.ForeignKey(blank=True, db_column='taxonomy_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_taxonomy_set', to='atencion.Taxonomy'),
        ),
    ]
