# Generated by Django 2.1.2 on 2018-10-05 17:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0013_level_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'InterventionType',
                'ordering': ('id',),
                'db_table': 'atencion_intervention_type',
                'verbose_name': 'InterventionType',
            },
        ),
    ]
