# Generated by Django 2.1.2 on 2018-10-12 04:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0015_pattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefiningCharacteristic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'DefiningCharacteristic',
                'verbose_name': 'DefiningCharacteristic',
                'ordering': ('name',),
                'db_table': 'atencion_def_char',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'DiagnosticTag',
                'verbose_name': 'DiagnosticTag',
                'ordering': ('name',),
                'db_table': 'atencion_diagnostic_tag',
            },
        ),
        migrations.AlterModelOptions(
            name='pattern',
            options={'ordering': ('name',), 'verbose_name': 'Pattern', 'verbose_name_plural': 'Pattern'},
        ),
        migrations.AddField(
            model_name='definingcharacteristic',
            name='diagnostic_tag',
            field=models.ManyToManyField(blank=True, db_table='atencion_def_char_diag_tag', related_name='def_char_diag_tag_set', to='atencion.DiagnosticTag'),
        ),
        migrations.AddField(
            model_name='definingcharacteristic',
            name='pattern',
            field=models.ManyToManyField(blank=True, db_table='atencion_def_char_pattern', related_name='def_char_pattern_set', to='atencion.Pattern'),
        ),
    ]
