# Generated by Django 2.1.2 on 2018-10-12 04:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0016_auto_20181012_0436'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'RelatedFactor',
                'verbose_name': 'RelatedFactor',
                'db_table': 'atencion_related_factor',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='diagnostictag',
            name='related_factor',
            field=models.ManyToManyField(blank=True, db_table='atencion_diag_tag_related', related_name='diag_tag_related_set', to='atencion.RelatedFactor'),
        ),
    ]
